# Generated by Django 4.0.3 on 2023-09-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='vip',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Created', max_length=200),
        ),
    ]
